name: dno-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - conda-forge:
      - ffmpeg
  - pip:
      # Regular pip dependencies
      - blobfile
      - einops
      - ftfy
      - gdown
      - h5py
      - matplotlib>=3.1.3
      - natsort
      - numpy>=1.22,<2.0.0
      - omegaconf
      - pillow>=9.2.0
      - psutil
      - pytorch-lightning>=1.9
      - PyYaml
      - regex
      - scikit-learn>=1.0.2
      - scipy>=1.7.3
      - seaborn
      - six
      - smplx==0.1.28
      - spacy>=3.3.1
      - tensorboard
      - torch_tb_profiler
      - torch-levenberg-marquardt
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchmetrics>0.11
      - torchvision==0.21.0
      - tqdm
      - trimesh
      # Git pip dependencies
      - git+https://github.com/openai/CLIP.git
      - git+https://github.com/mattloper/chumpy.git # Latest git version removes deprecated numpy imports
      # Extra index URLs
      - --extra-index-url https://download.pytorch.org/whl/cu126
